# Exercise

1. Use famous iris flower dataset from sklearn.datasets to predict flower species using SVM classifier.
2. Measure prediction score by using different Kernal Function
3. Find the best classifer and score for the Kernal Function

# Load the iris flower dataset

In [ ]:
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Understand the dataset
1. iris.DESCR > Complete description of dataset
2. iris.data > Data to learn. Each training set is 4 digit array of features. Total 150 training sets
3. iris.feature_names > Array of all 4 feature ['sepal length (cm)','sepal width cm)','petal length (cm)','petal width (cm)']
4. iris.filename > CSV file name
5. iris.target > The classification label. For every training set there is one classification label(0,1,2). Here 0 for setosa, 1 for versicolor and 2 for virginica
6. iris.target_names > the meaning of the features. Its a array >> ['setosa', 'versicolor', 'virginica']
From above details its clear that our data is 'iris.data' and labels are 'iris.target'

Each training example in iris.data is a array of iris.feature_names lets create a dataframe

# Set the Input and Target Column

In [ ]:
iris = datasets.load_iris()
iris_df=pd.DataFrame(iris.data)
iris_df['class']=iris.target

In [ ]:
x = iris_df.copy()

# Display the shape of the dataset with head and tail portion

In [ ]:
x.head(5)


0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [ ]:
x.tail(5)

0    1    2    3
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

# Preprocessing missing values

In [ ]:
x.isnull().sum()

0    0
1    0
2    0
3    0
dtype: int64

# Preprocessing Duplicate values

In [ ]:
x.duplicated().sum()

1

In [ ]:
x.drop_duplicates(inplace=True)

In [ ]:
x.duplicated().sum()

0

In [ ]:
x

0    1    2    3  class
0    5.1  3.5  1.4  0.2      0
1    4.9  3.0  1.4  0.2      0
2    4.7  3.2  1.3  0.2      0
3    4.6  3.1  1.5  0.2      0
4    5.0  3.6  1.4  0.2      0
..   ...  ...  ...  ...    ...
145  6.7  3.0  5.2  2.3      2
146  6.3  2.5  5.0  1.9      2
147  6.5  3.0  5.2  2.0      2
148  6.2  3.4  5.4  2.3      2
149  5.9  3.0  5.1  1.8      2

[150 rows x 5 columns]

#  Split the dataset into the Training set and Test set

In [ ]:
X = x.iloc[:, 0:-1]
Y = x.iloc[:, -1]

In [ ]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: class, Length: 150, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

# Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_Train = sc_X.fit_transform(X_Train)
X_Test = sc_X.transform(X_Test)

#   Fitting the classifier into the Training set

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_Train, Y_Train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
Y_Pred = classifier.predict(X_Test)

In [ ]:
classifier.score(X_Train,Y_Train)

0.9732142857142857

In [ ]:
classifier.score(X_Test,Y_Test)

0.9736842105263158

#   Predicting the test set results

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
cm = confusion_matrix(Y_Test, Y_Pred)

#   Display the confusion matrix

In [ ]:
print(confusion_matrix(Y_Test, Y_Pred))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


#   Display the Classification Report

In [ ]:
print(classification_report(Y_Test, Y_Pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



Try by using different Kernal function

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_Train, Y_Train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
Y_Pred = classifier.predict(X_Test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
cm = confusion_matrix(Y_Test, Y_Pred)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])